### ISSUE TITLE
[Feature Request] Discord (or similar) webhook notifications

### ISSUE THREAD

**Issue by mrrfv** [mrrfv/cloudflare-gateway-pihole-scripts#46]
CGPS is more of a "set-and-forget" script, meaning that if something happens to go wrong, it usually isn't noticed until it's too late and ads start showing up. It'd be nice to have a feature allowing the use of Discord (as well as Matrix, maybe with the use of [Matrix-Webhooks](https://matrix-webhooks.com/)) for error notifications and such.

**Comment by OneZK** [comment]
This is a great feature. While waiting for the repo owner to implement this kind of feature, my temporary solution is to enable email notification for errors. I forgot how I enabled but it is possible. During Cloudflare outage I got an email notification on my Gmail account from my repo regarding the failed runs. That was every 3 hours since I scheduled the script to run every 3 hours.  The downside of this method is that I have to delete the email notification one by one. Imagine 1 email notif from github every 3 hrs since the Cloudflare outage started, that's a lot of email.
