### ISSUE TITLE
It doesnt block twitch ads

### ISSUE THREAD

**Issue by kakakolaka** [mrrfv/cloudflare-gateway-pihole-scripts#74]
It doesnt block twitch ads, can you add ads from twitch to this script?

**Comment by mrrfv** [comment]
I heard that Twitch ads are notoriously hard to block, because they inject ads into the video stream directly from the server side, among other things. Fixing/bypassing this is impossible for a DNS ad blocker which is only capable of blocking domains used exclusively for serving ads and other undesirable content. Please use [uBlock Origin](https://github.com/gorhill/uBlock) in addition to CGPS to block Twitch ads more effectively.
