### ISSUE TITLE
block lists

### ISSUE THREAD

**Issue by suricloud** [mrrfv/cloudflare-gateway-pihole-scripts#9]
Hi, 
I see mullavad already added adguard dns list.
Also cgps script adds adguard dns, so its double now.

I hope you can add some of hagezi's list.

**Comment by mrrfv** [comment]
Hi, sorry for the delay.

As previously mentioned, Hagezi's lists cannot be added because even the most basic list, Multi LIGHT, has over 600,000 entries - more than double than what Cloudflare allows.

> I see mullavad already added adguard dns list.
> Also cgps script adds adguard dns, so its double now.

I don't understand. Did you mean that both Mullvad and the script use Adguard's lists, causing duplicates? I couldn't find any usage of Adguard lists in `get_recommended_filters.sh`, but that wouldn't be a problem anyway as duplicates are automatically removed.
